# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 23:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskQueueElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('command_json', models.CharField(max_length=512)),
                ('priority', models.IntegerField(default=100)),
                ('onfail_json', models.CharField(blank=True, max_length=512, null=True)),
                ('retries_left', models.IntegerField(default=3)),
                ('retry_minutes', models.IntegerField(default=2000)),
                ('cron', models.CharField(blank=True, max_length=32, null=True)),
                ('enqueue_time', models.DateTimeField(blank=True, null=True)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('finish_time', models.DateTimeField(blank=True, null=True)),
                ('pending', models.BooleanField(default=True)),
                ('success', models.BooleanField(default=False)),
                ('fail', models.BooleanField(default=False)),
                ('dependency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.TaskQueueElement')),
            ],
        ),
    ]
