# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-11 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_document_package_packagesession_packageversion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text=(
                    "Отметьте, если пользователь должен считаться активным."
                    " Уберите эту отметку вместо удаления учётной записи."
                ),
                verbose_name="Active",
            ),
        ),
    ]
