# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-19 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_auto_20171216_1909"),
    ]

    operations = [
        migrations.CreateModel(
            name="Snippet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                (
                    "url",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("style_json", models.CharField(max_length=256)),
                ("content_json", models.CharField(max_length=512)),
                (
                    "edit_perm",
                    models.CharField(default="@all", max_length=256),
                ),
                ("order", models.SmallIntegerField(default=0)),
                ("show_start", models.DateTimeField(blank=True, null=True)),
                ("show_end", models.DateTimeField(blank=True, null=True)),
                ("is_async", models.BooleanField(default=False)),
            ],
        ),
    ]
