# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-19 19:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_snippet"),
    ]

    operations = [
        migrations.RenameField(
            model_name="snippet",
            old_name="edit_perm",
            new_name="view_perm",
        ),
    ]
