# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-20 21:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_auto_20171219_1933"),
        ("core", "0005_auto_20171217_1815"),
    ]

    operations = []
