# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-23 11:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_merge_20171220_2123"),
        ("core", "0007_auto_20171223_1029"),
    ]

    operations = []
