# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-25 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_merge_20171223_1132"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RssFeedsToCache",
        ),
        migrations.AlterField(
            model_name="snippet",
            name="content_json",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text=(
                    "Отметьте, если пользователь должен считаться активным."
                    " Уберите эту отметку вместо удаления учётной записи."
                ),
                verbose_name="Действие",
            ),
        ),
    ]
