# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-25 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_auto_20171225_1011"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogFeed",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feed_id", models.CharField(max_length=32)),
                ("title", models.CharField(max_length=256)),
                (
                    "url",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("rss", models.CharField(max_length=256)),
                (
                    "rss_comments",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
    ]
