# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-25 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_blogfeed"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogfeed",
            name="show_author",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
