# Generated by Django 2.0.1 on 2018-01-02 09:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_auto_20180102_0905"),
        ("core", "0012_auto_20171230_1421"),
    ]

    operations = []
