# Generated by Django 2.0.1 on 2018-01-05 20:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_snippetpins"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SnippetPins",
            new_name="SnippetPin",
        ),
        migrations.AlterUniqueTogether(
            name="snippetpin",
            unique_together={("snippet", "user")},
        ),
    ]
