# Generated by Django 2.0.1 on 2018-01-12 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_auto_20180105_2029"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskqueueelement",
            name="log",
            field=models.TextField(blank=True),
        ),
    ]
