# Generated by Django 6.0.1 on 2026-09-05 17:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_blogfeed_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="package",
            name="download_perm",
        ),
        migrations.RemoveField(
            model_name="package",
            name="edit_perm",
        ),
        migrations.RemoveField(
            model_name="snippet",
            name="view_perm",
        ),
    ]
