# Generated by Django 6.0.1 on 2026-09-20 16:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_remove_package_download_perm_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="package",
            name="game",
        ),
        migrations.RemoveField(
            model_name="packagesession",
            name="package",
        ),
        migrations.RemoveField(
            model_name="packagesession",
            name="user",
        ),
        migrations.DeleteModel(
            name="PackageVersion",
        ),
        migrations.DeleteModel(
            name="Package",
        ),
        migrations.DeleteModel(
            name="PackageSession",
        ),
    ]
