"""
Django settings for ifdb project.

Generated by 'django-admin startproject' using Django 1.10.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
import socket
import os.path

IS_PROD = socket.gethostname() == 'ribby.mooskagh.com'

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
if IS_PROD:
    SECRET_KEY = open('/home/ifdb/configs/django-secret.txt').read().strip()
    DEBUG = False
    ALLOWED_HOSTS = ['db.mooskagh.com', 'db-staging.mooskagh.com']
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': 'ifdb',
            'USER': 'ifdb',
            'PASSWORD': open('/home/ifdb/configs/db-pass.txt').read().strip(),
            'HOST': '',
            'PORT': '',
        }
    }
    MEDIA_ROOT = os.path.abspath('/home/ifdb/uploads')
    if 'staging' in BASE_DIR:
        STATIC_ROOT = os.path.abspath('/home/ifdb/staging/static')
    else:
        STATIC_ROOT = os.path.abspath('/home/ifdb/static')

    EMAIL_HOST_PASSWORD = open('/home/ifdb/configs/gmail-pass.txt').read(
    ).strip()

else:
    SECRET_KEY = 'l3uja(27m53i#c)#9ziwmf*3n^e59eieal=3i$z0j@&$0i$!hr'
    DEBUG = True
    ALLOWED_HOSTS = []
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }
    MEDIA_ROOT = os.path.abspath('./uploads')
    EMAIL_HOST_PASSWORD = open('D:/tmp/gmail-pass.txt').read().strip()

ADMINS = [('Alexander Lyashuk', 'mooskagh@gmail.com')]
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'ersatzplut@gmail.com'
DEFAULT_FROM_EMAIL = 'ersatzplut@gmail.com'
SERVER_EMAIL = 'ersatzplut@gmail.com'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin', 'django.contrib.auth',
    'django.contrib.contenttypes', 'django.contrib.sessions',
    'django.contrib.messages', 'django.contrib.staticfiles', 'games'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'ifdb.permissioner.permissioner',
]

ROOT_URLCONF = 'ifdb.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ifdb.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME':
        'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = False

FILE_UPLOAD_PERMISSIONS = 0o640
FILE_UPLOAD_DIRECTORY_PERMISSIONS = 0o2750
STATIC_URL = '/static/'
MEDIA_URL = '/uploads/'

ACCOUNT_ACTIVATION_DAYS = 7
INCLUDE_AUTH_URLS = True
REGISTRATION_OPEN = True
