# Generated by Django 2.0.1 on 2018-02-03 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("contest", "0001_initial"),
        ("contest", "0002_auto_20180128_1918"),
        ("contest", "0003_remove_nomimation_description"),
        ("contest", "0004_auto_20180130_2113"),
        ("contest", "0005_competitionschedule_competition"),
        ("contest", "0006_auto_20180130_2116"),
        ("contest", "0007_competition_slug"),
        ("contest", "0008_competitionurlcategory_order"),
        ("contest", "0009_auto_20180203_1535"),
        ("contest", "0010_gamelist_order"),
    ]

    initial = True

    dependencies = [
        ("games", "0018_auto_20180113_1613"),
    ]

    operations = [
        migrations.CreateModel(
            name="Competition",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("slug", models.SlugField(default="", max_length=32)),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="CompetitionSchedule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("when", models.DateTimeField()),
                ("done", models.BooleanField()),
                ("show", models.BooleanField()),
                (
                    "title",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("command", models.TextField(blank=True, null=True)),
                (
                    "competition",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contest.Competition",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="CompetitionURL",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="CompetitionURLCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "symbolic_id",
                    models.SlugField(
                        blank=True, max_length=32, null=True, unique=True
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=255)),
                ("allow_cloning", models.BooleanField(default=True)),
                ("order", models.SmallIntegerField(default=0)),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="GameList",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="GameListEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rank", models.IntegerField(blank=True, null=True)),
                ("datetime", models.DateTimeField(blank=True, null=True)),
                ("comment", models.CharField(max_length=255)),
                (
                    "game",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="games.Game",
                    ),
                ),
                (
                    "gamelist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contest.GameList",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.AddField(
            model_name="competitionurl",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contest.CompetitionURLCategory",
            ),
        ),
        migrations.AddField(
            model_name="competitionurl",
            name="competition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contest.Competition",
            ),
        ),
        migrations.AddField(
            model_name="competitionurl",
            name="url",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="games.URL"
            ),
        ),
        migrations.CreateModel(
            name="CompetitionDocument",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(blank=True)),
                ("title", models.CharField(max_length=256)),
                ("text", models.TextField()),
                (
                    "view_perm",
                    models.CharField(default="@admin", max_length=256),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contest.Competition",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.AddField(
            model_name="gamelist",
            name="competition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contest.Competition",
            ),
        ),
        migrations.AddField(
            model_name="gamelist",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="gamelist",
            name="order",
            field=models.SmallIntegerField(default=0),
        ),
    ]
