# Generated by Django 2.0.1 on 2018-01-28 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0018_auto_20180113_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='CompetitionSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField()),
                ('done', models.BooleanField()),
                ('show', models.BooleanField()),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('command', models.TextField(blank=True, null=True)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='CompetitionURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='CompetitionURLCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbolic_id', models.SlugField(blank=True, max_length=32, null=True, unique=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('allow_cloning', models.BooleanField(default=True)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='GameList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='GameListEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('comment', models.CharField(max_length=255)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.Game')),
                ('gamelist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.GameList')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Nomimation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Competition')),
                ('gamelist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contest.GameList')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='competitionurl',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.CompetitionURLCategory'),
        ),
        migrations.AddField(
            model_name='competitionurl',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Competition'),
        ),
        migrations.AddField(
            model_name='competitionurl',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.URL'),
        ),
    ]
