# Generated by Django 2.0.1 on 2018-02-03 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contest", "0001_squashed_0010_gamelist_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competition",
            name="slug",
            field=models.SlugField(max_length=32),
        ),
        migrations.AlterField(
            model_name="competitionschedule",
            name="competition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contest.Competition",
            ),
        ),
        migrations.AlterField(
            model_name="gamelistentry",
            name="comment",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
