# Generated by Django 2.0.1 on 2018-01-30 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_auto_20180128_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomimation',
            name='description',
        ),
    ]
