# Generated by Django 2.0.1 on 2018-02-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contest", "0003_competition_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamelistentry",
            name="datetime",
            field=models.DateField(blank=True, null=True),
        ),
    ]
