# Generated by Django 2.0.1 on 2018-01-30 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contest", "0003_remove_nomimation_description"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Nomimation",
            new_name="CompetitionNomination",
        ),
    ]
