# Generated by Django 2.0.1 on 2018-01-30 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0005_competitionschedule_competition'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competitiondocument',
            options={'default_permissions': ()},
        ),
    ]
