# Generated by Django 2.0.1 on 2018-02-10 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contest", "0006_auto_20180207_2133"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="competition",
            name="published",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
