# Generated by Django 2.0.1 on 2018-02-03 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contest", "0008_competitionurlcategory_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="competitionnomination",
            name="competition",
        ),
        migrations.RemoveField(
            model_name="competitionnomination",
            name="gamelist",
        ),
        migrations.AddField(
            model_name="gamelist",
            name="competition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contest.Competition",
            ),
        ),
        migrations.AddField(
            model_name="gamelist",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name="CompetitionNomination",
        ),
    ]
