# Generated by Django 2.0.1 on 2018-02-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0009_auto_20180203_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamelist',
            name='order',
            field=models.SmallIntegerField(default=0),
        ),
    ]
