# Generated by Django 2.0.1 on 2018-02-22 19:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contest", "0010_gamelistentry_position"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gamelistentry",
            old_name="position",
            new_name="result",
        ),
    ]
