# Generated by Django 2.0.1 on 2019-07-31 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contest", "0012_competitionvote"),
    ]

    operations = [
        migrations.AddField(
            model_name="competitiondocument",
            name="order",
            field=models.SmallIntegerField(default=0),
        ),
    ]
