# Generated by Django 2.0.1 on 2019-09-22 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0021_auto_20190728_1928'),
        ('contest', '0014_auto_20190803_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.SlugField(blank=True, max_length=32, null=True)),
                ('text', models.TextField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Game')),
            ],
            options={
                'default_permissions': (),
            },
        ),
    ]
