# Generated by Django 2.0.1 on 2019-09-22 10:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0021_auto_20190728_1928"),
        ("contest", "0015_competitionquestions"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CompetitionQuestions",
            new_name="CompetitionQuestion",
        ),
    ]
