# Generated by Django 6.0.1 on 2026-09-05 17:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "contest",
            "0018_alter_competition_id_alter_competitiondocument_id_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="competitiondocument",
            name="view_perm",
        ),
        migrations.RemoveField(
            model_name="competitionvote",
            name="perm",
        ),
    ]
