# Generated by Django 6.0.1 on 2026-05-30 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("games", "0022_game_description_attribution"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GameSource",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=2048,
                        null=True,
                        verbose_name="URL",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("APERO", "Apero"),
                            ("IFWIKI", "IFWiki"),
                            ("QSP", "QSP"),
                            ("INSTEAD", "INSTEAD"),
                            ("QUESTBOOK", "QuestBook"),
                            ("IFICTION", "ifiction"),
                            ("RILARHIV", "Rilarhiv"),
                            ("CURRENT_TEXT", "Current text"),
                            ("STICKY_NOTE", "Sticky note"),
                        ],
                        max_length=16,
                        verbose_name="Type",
                    ),
                ),
                (
                    "failing_since",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Failing since"
                    ),
                ),
                (
                    "last_attempt",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last attempt"
                    ),
                ),
                (
                    "last_error",
                    models.TextField(
                        blank=True, null=True, verbose_name="Last error"
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="GameSourceFetch",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raw_content", models.TextField(verbose_name="Raw content")),
                (
                    "filtered_content",
                    models.TextField(verbose_name="Filtered content"),
                ),
                (
                    "filtered_content_hash",
                    models.CharField(
                        db_index=True,
                        max_length=64,
                        verbose_name="Filtered content hash",
                    ),
                ),
                (
                    "first_fetch",
                    models.DateTimeField(verbose_name="First fetch"),
                ),
                (
                    "last_fetch",
                    models.DateTimeField(verbose_name="Last fetch"),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="curation.gamesource",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="GameTicket",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "auto_updates",
                    models.CharField(
                        choices=[
                            ("REJECT", "Reject incoming imports"),
                            ("PROPOSE", "Propose for review"),
                            ("ACCEPT", "Auto-approve and apply"),
                        ],
                        default="ACCEPT",
                        max_length=16,
                        verbose_name="Auto-update policy",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(default=100, verbose_name="Priority"),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("SETTLED", "Settled"),
                            ("IN_PROGRESS", "In progress"),
                            ("NEEDS_ATTENTION", "Needs attention"),
                        ],
                        default="IN_PROGRESS",
                        max_length=16,
                        verbose_name="State",
                    ),
                ),
                (
                    "attention_reason",
                    models.TextField(
                        blank=True, null=True, verbose_name="Attention reason"
                    ),
                ),
                (
                    "creation_time",
                    models.DateTimeField(verbose_name="Created at"),
                ),
                (
                    "edit_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last edit"
                    ),
                ),
                (
                    "game",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="games.game",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.AddField(
            model_name="gamesource",
            name="ticket",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="curation.gameticket",
            ),
        ),
        migrations.CreateModel(
            name="GameReconciliation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "proposed_at",
                    models.DateTimeField(verbose_name="Proposed at"),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Approved at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PROPOSED", "Proposed"),
                            ("APPLIED", "Applied"),
                            ("REJECTED", "Rejected"),
                        ],
                        max_length=16,
                        verbose_name="Status",
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("AUTO_IMPORT", "Automatic import"),
                            ("MANUAL_EDIT", "Manual edit"),
                            ("USER_SUGGESTION", "User suggestion"),
                        ],
                        max_length=16,
                        verbose_name="Origin",
                    ),
                ),
                (
                    "canonical_text",
                    models.TextField(verbose_name="Canonical text"),
                ),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_reconciliation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="curation.gamereconciliation",
                    ),
                ),
                (
                    "used_sources",
                    models.ManyToManyField(
                        blank=True, to="curation.gamesourcefetch"
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="curation.gameticket",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="GameTicketAuditLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(verbose_name="Created at"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[], max_length=32, verbose_name="Kind"
                    ),
                ),
                (
                    "field",
                    models.CharField(
                        blank=True,
                        choices=[],
                        max_length=32,
                        null=True,
                        verbose_name="Field",
                    ),
                ),
                ("old_id", models.IntegerField(blank=True, null=True)),
                ("new_id", models.IntegerField(blank=True, null=True)),
                ("old_text", models.TextField(blank=True, null=True)),
                ("new_text", models.TextField(blank=True, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="curation.gameticket",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="GameTicketComment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("USER_FEEDBACK", "User feedback"),
                            ("MODS_COMMENT", "Moderator comment"),
                            ("NOTE_FOR_AI", "Note for AI"),
                            ("STATUS_MESSAGE", "Status message"),
                            ("EMAIL_RESPONSE", "Email response"),
                        ],
                        max_length=16,
                        verbose_name="Type",
                    ),
                ),
                ("text", models.TextField(verbose_name="Text")),
                (
                    "creation_time",
                    models.DateTimeField(verbose_name="Created at"),
                ),
                (
                    "reply_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="curation.gameticketcomment",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="curation.gameticket",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
    ]
