# Generated by Django 6.0.1 on 2026-05-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gameticketauditlog",
            name="kind",
            field=models.CharField(
                choices=[
                    ("INITIAL_IMPORT", "Initial import from old importer")
                ],
                max_length=32,
                verbose_name="Kind",
            ),
        ),
    ]
