# Generated by Django 6.0.1 on 2026-05-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamesource",
            name="type",
            field=models.CharField(
                choices=[
                    ("APERO", "Apero"),
                    ("IFWIKI", "IFWiki"),
                    ("QSP", "QSP"),
                    ("PLUT", "Plut"),
                    ("INSTEAD", "INSTEAD"),
                    ("QUESTBOOK", "QuestBook"),
                    ("IFICTION", "ifiction"),
                    ("RILARHIV", "Rilarhiv"),
                    ("CURRENT_TEXT", "Current text"),
                    ("STICKY_NOTE", "Sticky note"),
                ],
                max_length=16,
                verbose_name="Type",
            ),
        ),
    ]
