# Generated by Django 6.0.1 on 2026-05-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curation", "0002_alter_gameticketauditlog_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamesource",
            name="created_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Created at"
            ),
        ),
        migrations.AlterField(
            model_name="gameticketauditlog",
            name="field",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AUTO_UPDATES", "Auto-update policy"),
                    ("STATE", "State"),
                ],
                max_length=32,
                null=True,
                verbose_name="Field",
            ),
        ),
        migrations.AlterField(
            model_name="gameticketauditlog",
            name="kind",
            field=models.CharField(
                choices=[
                    ("INITIAL_IMPORT", "Initial import from old importer"),
                    ("FIELD_CHANGE", "Field changed"),
                ],
                max_length=32,
                verbose_name="Kind",
            ),
        ),
    ]
