# Generated by Django 6.0.1 on 2026-05-31 07:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curation", "0003_rename_gamesourcefetch_canonical_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceDiscoveryStatus",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("APERO", "Apero"),
                            ("IFWIKI", "IFWiki"),
                            ("QSP", "QSP"),
                            ("PLUT", "Plut"),
                            ("INSTEAD", "INSTEAD"),
                            ("QUESTBOOK", "QuestBook"),
                            ("IFICTION", "ifiction"),
                            ("RILARHIV", "Rilarhiv"),
                            ("CURRENT_TEXT", "Current text"),
                            ("STICKY_NOTE", "Sticky note"),
                        ],
                        max_length=16,
                        verbose_name="Source type",
                    ),
                ),
                (
                    "first_seen",
                    models.DateTimeField(verbose_name="First seen"),
                ),
                ("last_seen", models.DateTimeField(verbose_name="Last seen")),
                (
                    "is_error",
                    models.BooleanField(default=False, verbose_name="Error"),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Error message"
                    ),
                ),
                (
                    "new_count",
                    models.IntegerField(default=0, verbose_name="New games"),
                ),
                (
                    "existing_count",
                    models.IntegerField(
                        default=0, verbose_name="Existing sources"
                    ),
                ),
                (
                    "missing_count",
                    models.IntegerField(
                        default=0, verbose_name="Missing sources"
                    ),
                ),
            ],
            options={
                "default_permissions": (),
                "indexes": [
                    models.Index(
                        fields=["source_type", "-last_seen"],
                        name="curation_so_source__83a1c7_idx",
                    )
                ],
            },
        ),
    ]
