# Generated by Django 6.0.1 on 2026-05-31 08:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curation", "0004_sourcediscoverystatus"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sourcediscoverystatus",
            name="existing_count",
        ),
        migrations.RemoveField(
            model_name="sourcediscoverystatus",
            name="missing_count",
        ),
        migrations.RemoveField(
            model_name="sourcediscoverystatus",
            name="new_count",
        ),
        migrations.AddField(
            model_name="gamesource",
            name="missing_since",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Missing since"
            ),
        ),
        migrations.AddField(
            model_name="sourcediscoverystatus",
            name="existing_ids",
            field=models.JSONField(
                default=list, verbose_name="Existing sources"
            ),
        ),
        migrations.AddField(
            model_name="sourcediscoverystatus",
            name="missing_ids",
            field=models.JSONField(
                default=list, verbose_name="Missing sources"
            ),
        ),
        migrations.AddField(
            model_name="sourcediscoverystatus",
            name="new_ids",
            field=models.JSONField(default=list, verbose_name="New sources"),
        ),
        migrations.AddField(
            model_name="sourcediscoverystatus",
            name="newly_missing_ids",
            field=models.JSONField(
                default=list, verbose_name="Newly missing sources"
            ),
        ),
    ]
