# Generated by OpenCode on 2026-05-31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "curation",
            "0005_remove_sourcediscoverystatus_existing_count_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="sourcediscoverystatus",
            old_name="missing_ids",
            new_name="absent_ids",
        ),
        migrations.AlterField(
            model_name="sourcediscoverystatus",
            name="absent_ids",
            field=models.JSONField(
                default=list, verbose_name="Absent sources"
            ),
        ),
        migrations.AddField(
            model_name="sourcediscoverystatus",
            name="duplicate_id_clusters",
            field=models.JSONField(
                default=list, verbose_name="Duplicate source clusters"
            ),
        ),
        migrations.AddField(
            model_name="sourcediscoverystatus",
            name="unused_ids",
            field=models.JSONField(
                default=list, verbose_name="Unused sources"
            ),
        ),
    ]
