# Generated by Django 6.0.1 on 2026-06-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curation", "0007_add_source_attached_audit_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamehistoryauditlog",
            name="field",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AUTO_UPDATES", "Auto-update policy"),
                    ("STATE", "State"),
                    ("CANONICAL_TEXT", "Canonical text"),
                    ("PRIORITY", "Priority"),
                ],
                max_length=32,
                null=True,
                verbose_name="Field",
            ),
        ),
    ]
