# Generated by Django 6.0.1 on 2026-06-01 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curation", "0009_remove_gameedit_parent_edit_gameedit_passes"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnrichmentRule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Order"
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(default=True, verbose_name="Enabled"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Description"
                    ),
                ),
                (
                    "condition",
                    models.TextField(blank=True, verbose_name="Condition"),
                ),
                ("action", models.TextField(verbose_name="Action")),
            ],
            options={
                "ordering": ["order", "pk"],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="GenreMapping",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tag",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Free-text tag",
                    ),
                ),
                (
                    "genre_slug",
                    models.CharField(max_length=32, verbose_name="Genre slug"),
                ),
                (
                    "replace",
                    models.BooleanField(
                        default=True, verbose_name="Replace original tag"
                    ),
                ),
            ],
            options={
                "ordering": ["tag"],
                "default_permissions": (),
            },
        ),
    ]
