# Generated by OpenCode on 2026-06-01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curation", "0010_enrichmentrule_genremapping"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameedit",
            name="previous_canonical_text",
            field=models.TextField(
                blank=True, null=True, verbose_name="Previous canonical text"
            ),
        ),
    ]
