# Generated by Django 6.0.1 on 2026-06-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curation", "0013_gameedit_proposed_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamehistoryauditlog",
            name="field",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AUTO_UPDATES", "Auto-update policy"),
                    ("STATE", "State"),
                ],
                max_length=32,
                null=True,
                verbose_name="Field",
            ),
        ),
    ]
