# Generated by Django 6.0.1 on 2026-06-02 21:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curation", "0016_add_source_detached_audit_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmmodel",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Updated at"
            ),
        ),
    ]
