# Generated by Django 6.0.1 on 2026-06-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curation", "0028_alter_gameedit_origin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamehistoryauditlog",
            name="kind",
            field=models.CharField(
                choices=[
                    ("INITIAL_IMPORT", "Initial import from old importer"),
                    ("SOURCE_ATTACHED", "Source attached"),
                    ("SOURCE_DETACHED", "Source detached"),
                    ("GAME_MERGED", "Game merged"),
                    ("AUTO_UPDATE_SCHEDULED", "Automatic update scheduled"),
                    ("FIELD_CHANGE", "Field changed"),
                ],
                max_length=32,
                verbose_name="Kind",
            ),
        ),
    ]
