# Generated by Django 6.0.1 on 2026-09-04 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curation", "0031_alter_gamehistory_game"),
        (
            "games",
            "0026_remove_game_games_game_state_redirect_target_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="gameedit",
            name="game",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="games.game",
            ),
        ),
        migrations.AddField(
            model_name="gamehistoryauditlog",
            name="game",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="games.game",
            ),
        ),
        migrations.AddField(
            model_name="gamehistorycomment",
            name="game",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="games.game",
            ),
        ),
        migrations.AddField(
            model_name="gamesource",
            name="game",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="games.game",
            ),
        ),
        migrations.AddField(
            model_name="llmtrajectory",
            name="game",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="games.game",
            ),
        ),
    ]
