# Generated by Django 6.0.1 on 2026-09-04 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curation", "0033_backfill_game_from_history"),
        (
            "games",
            "0026_remove_game_games_game_state_redirect_target_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="gameedit",
            name="curation_gameedit_one_proposed_per_history",
        ),
        migrations.RemoveField(
            model_name="gamehistoryauditlog",
            name="history",
        ),
        migrations.RemoveField(
            model_name="gamehistorycomment",
            name="history",
        ),
        migrations.RemoveField(
            model_name="gamesource",
            name="history",
        ),
        migrations.RemoveField(
            model_name="llmtrajectory",
            name="history",
        ),
        migrations.AlterField(
            model_name="gameedit",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="games.game"
            ),
        ),
        migrations.AlterField(
            model_name="gamehistoryauditlog",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="games.game"
            ),
        ),
        migrations.AlterField(
            model_name="gamehistorycomment",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="games.game"
            ),
        ),
        migrations.AlterField(
            model_name="llmtrajectory",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="games.game"
            ),
        ),
        migrations.AddConstraint(
            model_name="gameedit",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "PROPOSED")),
                fields=("game",),
                name="curation_gameedit_one_proposed_per_game",
            ),
        ),
        migrations.RemoveField(
            model_name="gameedit",
            name="history",
        ),
    ]
