# Generated by Django 6.0.1 on 2026-09-04 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curation", "0034_remove_curation_history_fk"),
        (
            "games",
            "0026_remove_game_games_game_state_redirect_target_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="gameedit",
            name="curation_gameedit_one_proposed_per_game",
        ),
        migrations.RenameModel(
            old_name="GameEdit",
            new_name="GameRevision",
        ),
        migrations.RenameField(
            model_name="gamerevision",
            old_name="proposed_at",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="gamerevision",
            old_name="approved_at",
            new_name="published_at",
        ),
        migrations.RenameField(
            model_name="gamerevision",
            old_name="proposed_by",
            new_name="created_by",
        ),
        migrations.RenameField(
            model_name="gamerevision",
            old_name="approver",
            new_name="published_by",
        ),
        migrations.AlterField(
            model_name="gamerevision",
            name="created_at",
            field=models.DateTimeField(verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="gamerevision",
            name="published_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Published at"
            ),
        ),
        migrations.AlterField(
            model_name="gamerevision",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_game_revisions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="gamerevision",
            name="status",
            field=models.CharField(
                choices=[
                    ("PROPOSED", "Proposed"),
                    ("PUBLISHED", "Published"),
                    ("REJECTED", "Rejected"),
                ],
                max_length=16,
                verbose_name="Status",
            ),
        ),
        migrations.AddConstraint(
            model_name="gamerevision",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "PROPOSED")),
                fields=("game",),
                name="curation_gamerevision_one_proposed_per_game",
            ),
        ),
    ]
