# Generated by Django 6.0.1 on 2026-09-04 20:13

import json
from collections import defaultdict
from collections.abc import Iterator
from typing import Any

from django.apps.registry import Apps
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.utils import timezone


def _dump(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False)


def _canonical_games(apps: Apps, db_alias: str) -> Iterator[tuple[Any, str]]:
    Game = apps.get_model("games", "Game")
    GameAuthor = apps.get_model("games", "GameAuthor")
    GameAuthorRole = apps.get_model("games", "GameAuthorRole")
    GameDescriptionAttribution = apps.get_model(
        "games", "GameDescriptionAttribution"
    )
    GameTag = apps.get_model("games", "GameTag")
    GameTagCategory = apps.get_model("games", "GameTagCategory")
    GameURL = apps.get_model("games", "GameURL")
    GameURLCategory = apps.get_model("games", "GameURLCategory")
    PersonalityAlias = apps.get_model("games", "PersonalityAlias")
    URL = apps.get_model("games", "URL")

    games = list(
        Game.objects
        .using(db_alias)
        .filter(state="PUBLISHED")
        .only("id", "title", "release_date", "description")
    )
    game_ids = [game.id for game in games]

    roles = {
        role.id: (role.symbolic_id, role.order)
        for role in GameAuthorRole.objects.using(db_alias).all()
    }
    aliases = dict(
        PersonalityAlias.objects.using(db_alias).values_list("id", "name")
    )
    authors = defaultdict(list)
    for game_id, role_id, author_id in (
        GameAuthor.objects
        .using(db_alias)
        .filter(game_id__in=game_ids)
        .values_list("game_id", "role_id", "author_id")
    ):
        role, order = roles[role_id]
        if role:
            authors[game_id].append((
                order,
                role,
                author_id,
                aliases[author_id],
            ))

    tag_categories = {
        category.id: (category.symbolic_id, category.order)
        for category in GameTagCategory.objects.using(db_alias).all()
    }
    tags = {
        tag.id: (*tag_categories[tag.category_id], tag.symbolic_id, tag.name)
        for tag in GameTag.objects.using(db_alias).all()
    }
    game_tags = defaultdict(list)
    for game_id, tag_id in (
        Game.tags.through.objects
        .using(db_alias)
        .filter(game_id__in=game_ids)
        .values_list("game_id", "gametag_id")
    ):
        game_tags[game_id].append((tag_id, *tags[tag_id]))

    url_categories = {
        category.id: (category.symbolic_id, category.order)
        for category in GameURLCategory.objects.using(db_alias).all()
    }
    urls = dict(URL.objects.using(db_alias).values_list("id", "original_url"))
    game_urls = defaultdict(list)
    for game_id, category_id, url_id, description in (
        GameURL.objects
        .using(db_alias)
        .filter(game_id__in=game_ids)
        .values_list("game_id", "category_id", "url_id", "description")
    ):
        category, order = url_categories[category_id]
        game_urls[game_id].append((
            order,
            category,
            url_id,
            description,
            urls[url_id],
        ))

    attribution_names = dict(
        GameDescriptionAttribution.objects.using(db_alias).values_list(
            "id", "name"
        )
    )
    attributions = defaultdict(list)
    attribution_through = Game.description_attributions.through
    for game_id, attribution_id in (
        attribution_through.objects
        .using(db_alias)
        .filter(game_id__in=game_ids)
        .values_list("game_id", "gamedescriptionattribution_id")
    ):
        attributions[game_id].append((
            attribution_id,
            attribution_names[attribution_id],
        ))

    for game in games:
        lines = []
        if game.title:
            lines.append(f"- name: {_dump(game.title)}")
        if game.release_date:
            lines.append(
                f"- release_date: {_dump(game.release_date.isoformat())}"
            )

        author_lines = []
        by_role = defaultdict(list)
        for order, role, author_id, name in authors[game.id]:
            by_role[(order, role)].append((author_id, name))
        for role_key in sorted(by_role):
            _, role = role_key
            author_lines.append(f"  - {role}:")
            for author_id, name in sorted(by_role[role_key]):
                author_lines.append(f"    - {author_id}  # {_dump(name)}")
        if author_lines:
            lines.extend(["- personalities:", *author_lines])

        tag_lines = []
        by_category = defaultdict(list)
        for tag_id, category, order, slug, name in game_tags[game.id]:
            by_category[(order, category)].append((tag_id, slug, name))
        for category_key in sorted(by_category):
            _, category = category_key
            category_tags = by_category[category_key]
            category_tags.sort(
                key=lambda tag: (0, tag[1]) if tag[1] else (1, tag[2])
            )
            for tag_id, slug, name in category_tags:
                if slug:
                    tag_lines.append(f"  - {_dump(slug)}")
                else:
                    item = _dump([category, tag_id])
                    tag_lines.append(f"  - {item}  # {_dump(name)}")
        if tag_lines:
            lines.extend(["- tags:", *tag_lines])

        url_lines = []
        by_category = defaultdict(list)
        for order, category, url_id, description, original in game_urls[
            game.id
        ]:
            by_category[(order, category)].append((
                url_id,
                description,
                original,
            ))
        for category_key in sorted(by_category):
            _, category = category_key
            for url_id, description, original in sorted(
                by_category[category_key], key=lambda url: url[0]
            ):
                label = f"{_dump(description)} " if description else ""
                item = _dump([category, description or "", url_id])
                url_lines.append(f"  - {item}  # {label}{_dump(original)}")
        if url_lines:
            lines.extend(["- urls:", *url_lines])

        attribution_lines = [
            f"  - {attribution_id}  # {_dump(name)}"
            for attribution_id, name in sorted(attributions[game.id])
        ]
        if attribution_lines:
            lines.extend(["- attributions:", *attribution_lines])

        yield (
            game,
            "---\n" + "\n".join(lines) + "\n---\n" + (game.description or ""),
        )


def backfill_game_revisions(
    apps: Apps, schema_editor: BaseDatabaseSchemaEditor
) -> None:
    GameRevision = apps.get_model("curation", "GameRevision")
    db_alias = schema_editor.connection.alias
    revisions = GameRevision.objects.using(db_alias)
    revisions.filter(status="APPLIED").update(status="PUBLISHED")

    latest_by_game = {}
    for revision in revisions.filter(status="PUBLISHED").order_by(
        "game_id", "-published_at", "-created_at", "-id"
    ):
        latest_by_game.setdefault(revision.game_id, revision)

    timestamp = timezone.now()
    new_revisions = []
    predecessors = []
    for game, canonical_text in _canonical_games(apps, db_alias):
        previous = latest_by_game.get(game.id)
        if previous and previous.canonical_text.rstrip(
            "\n"
        ) == canonical_text.rstrip("\n"):
            continue
        new_revisions.append(
            GameRevision(
                game_id=game.id,
                created_at=timestamp,
                published_at=timestamp,
                status="PUBLISHED",
                origin="BACKFILL",
                previous_canonical_text=(
                    previous.canonical_text if previous is not None else ""
                ),
                canonical_text=canonical_text,
            )
        )
        predecessors.append(previous)

    revisions.bulk_create(new_revisions, batch_size=500)
    through = GameRevision.used_sources.through
    links = []
    predecessor_ids = [revision.id for revision in predecessors if revision]
    source_ids = defaultdict(list)
    for revision_id, source_id in (
        through.objects
        .using(db_alias)
        .filter(gamerevision_id__in=predecessor_ids)
        .values_list("gamerevision_id", "gamesourcefetch_id")
    ):
        source_ids[revision_id].append(source_id)
    for revision, previous in zip(new_revisions, predecessors, strict=True):
        if previous is None:
            continue
        links.extend(
            through(
                gamerevision_id=revision.id,
                gamesourcefetch_id=source_id,
            )
            for source_id in source_ids[previous.id]
        )
    through.objects.using(db_alias).bulk_create(links, batch_size=1000)


def reverse_backfill(
    apps: Apps, schema_editor: BaseDatabaseSchemaEditor
) -> None:
    GameRevision = apps.get_model("curation", "GameRevision")
    revisions = GameRevision.objects.using(schema_editor.connection.alias)
    revisions.filter(origin="BACKFILL").delete()
    revisions.filter(status="PUBLISHED").update(status="APPLIED")


class Migration(migrations.Migration):
    dependencies = [
        ("curation", "0035_rename_gameedit_to_gamerevision"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamerevision",
            name="origin",
            field=models.CharField(
                choices=[
                    ("AUTO_IMPORT", "Automatic import"),
                    ("MANUAL_EDIT", "Manual edit"),
                    ("USER_SUGGESTION", "User suggestion"),
                    ("BACKFILL", "Backfill"),
                    ("ROLLBACK", "Rollback"),
                    ("PARTIAL_ROLLBACK", "Partial rollback"),
                    ("REAPPLICATION", "Reapplication"),
                    ("PARTIAL_REAPPLY", "Partial reapplication"),
                ],
                max_length=16,
                verbose_name="Origin",
            ),
        ),
        migrations.RunPython(backfill_game_revisions, reverse_backfill),
    ]
