# Generated by Django 6.0.1 on 2026-09-05 06:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("curation", "0036_backfill_game_revisions"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="gamerevision",
            name="curation_gamerevision_one_proposed_per_game",
        ),
    ]
