# Generated by Django 6.0.1 on 2026-09-05 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "curation",
            "0037_remove_gamerevision_curation_gamerevision_one_proposed_per_game",
        ),
        ("games", "0027_gamerevision"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="llmtrajectory",
                    name="edit",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="games.gamerevision",
                    ),
                ),
                migrations.DeleteModel(
                    name="GameRevision",
                ),
            ],
            database_operations=[],
        ),
    ]
