# Generated by Django 6.0.1 on 2026-09-05 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curation", "0038_alter_llmtrajectory_edit_delete_gamerevision"),
        ("games", "0029_alter_gamerevision_origin"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameCuration",
            fields=[
                (
                    "game",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="curation",
                        serialize=False,
                        to="games.game",
                    ),
                ),
                (
                    "auto_updates",
                    models.CharField(
                        choices=[
                            ("REJECT", "Reject incoming imports"),
                            ("PROPOSE", "Propose for review"),
                            ("ACCEPT", "Auto-approve and apply"),
                        ],
                        default="ACCEPT",
                        max_length=16,
                        verbose_name="Auto-update policy",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("SETTLED", "Settled"),
                            (
                                "SCHEDULED_FOR_UPDATE",
                                "Scheduled for automatic update",
                            ),
                            ("PROCESSING", "Processing"),
                            ("NEEDS_ATTENTION", "Needs attention"),
                            ("ABANDONED", "Abandoned"),
                        ],
                        default="SCHEDULED_FOR_UPDATE",
                        max_length=32,
                        verbose_name="State",
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True, null=True, verbose_name="Note"
                    ),
                ),
                (
                    "processing_started_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Processing started at",
                    ),
                ),
                (
                    "processing_task_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Processing task id",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
    ]
