# Generated by Django 6.0.1 on 2026-09-05 12:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("curation", "0040_backfill_gamecuration_from_history"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GameHistory",
        ),
    ]
