# Generated by Django 6.0.1 on 2026-09-11 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curation", "0041_delete_gamehistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamecuration",
            name="exclude_overrides",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Exclude overrides"
            ),
        ),
        migrations.AddField(
            model_name="gamecuration",
            name="include_overrides",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Include overrides"
            ),
        ),
    ]
