# Generated by Django 6.0.1 on 2026-09-23 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curation", "0044_alter_gamesource_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamesource",
            name="type",
            field=models.CharField(
                choices=[
                    ("APERO", "Apero"),
                    ("IFWIKI", "IFWiki"),
                    ("QSP", "QSP"),
                    ("PLUT", "Plut"),
                    ("INSTEAD", "INSTEAD"),
                    ("QUESTBOOK", "QuestBook"),
                    ("IFICTION", "ifiction"),
                    ("RILARHIV", "Rilarhiv"),
                    ("AXMA", "AXMA"),
                    ("HYPERBOOK", "Hyperbook"),
                    ("CURRENT_TEXT", "Current text"),
                    ("STICKY_NOTE", "Sticky note"),
                ],
                max_length=16,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="sourcediscoverystatus",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("APERO", "Apero"),
                    ("IFWIKI", "IFWiki"),
                    ("QSP", "QSP"),
                    ("PLUT", "Plut"),
                    ("INSTEAD", "INSTEAD"),
                    ("QUESTBOOK", "QuestBook"),
                    ("IFICTION", "ifiction"),
                    ("RILARHIV", "Rilarhiv"),
                    ("AXMA", "AXMA"),
                    ("HYPERBOOK", "Hyperbook"),
                    ("CURRENT_TEXT", "Current text"),
                    ("STICKY_NOTE", "Sticky note"),
                ],
                max_length=16,
                verbose_name="Source type",
            ),
        ),
    ]
