# Generated by Django 2.0.1 on 2018-01-14 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_addr', models.CharField(blank=True, max_length=50, null=True)),
                ('session', models.CharField(blank=True, max_length=32, null=True)),
                ('timestamp', models.DateTimeField()),
                ('perm', models.TextField(blank=True, null=True)),
                ('is_mutation', models.BooleanField()),
                ('obj_type', models.CharField(blank=True, max_length=32, null=True)),
                ('obj_id', models.IntegerField(blank=True, null=True)),
                ('obj2_type', models.CharField(blank=True, max_length=32, null=True)),
                ('obj2_id', models.IntegerField(blank=True, null=True)),
                ('action', models.CharField(max_length=32)),
                ('before', models.TextField(blank=True, null=True)),
                ('after', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_permissions': (),
            },
        ),
    ]
