# Generated by Django 2.0.1 on 2018-01-14 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moder", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userlog",
            name="useragent",
            field=models.TextField(blank=True, null=True),
        ),
    ]
