# Generated by Django 6.0.1 on 2026-09-05 17:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("moder", "0003_alter_userlog_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userlog",
            name="perm",
        ),
    ]
