# Generated by Django 6.0.1 on 2026-08-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("play", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playable",
            name="template",
            field=models.SlugField(),
        ),
        migrations.DeleteModel(
            name="Template",
        ),
    ]
