# Generated by Django 6.0.1 on 2026-08-30 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("play", "0002_alter_playable_template_delete_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="playable",
            name="template_version",
            field=models.CharField(default="1.0", max_length=32),
            preserve_default=False,
        ),
    ]
