# Generated by Django 6.0.1 on 2026-08-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("play", "0003_playable_template_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="playable",
            name="template_config",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
