# Generated by Django 6.0.1 on 2026-09-06 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0032_delete_admin_tag_category"),
        ("play", "0004_playable_template_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="playable",
            name="game_url",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="playables",
                to="games.gameurl",
            ),
        ),
        migrations.AddField(
            model_name="playable",
            name="state",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("BUILDING", "Building"),
                    ("READY", "Ready"),
                    ("ERROR", "Error"),
                ],
                default="PENDING",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="playable",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
