# Generated by Django 6.0.1 on 2026-09-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("play", "0006_seed_playable_domain_workflow"),
    ]

    operations = [
        migrations.AddField(
            model_name="playable",
            name="visible",
            field=models.BooleanField(default=True),
        ),
    ]
