# Generated by Django 6.0.1 on 2026-09-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("play", "0008_playsession_playsegment"),
    ]

    operations = [
        migrations.AddField(
            model_name="playable",
            name="player_name",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="playable",
            name="player_url",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
