# Generated by Django 6.0.1 on 2026-09-19 19:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("play", "0009_playable_player_name_playable_player_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playsegment",
            name="active_seconds",
            field=models.FloatField(default=0.0),
        ),
    ]
