# Generated by Django 6.0.1 on 2026-09-19 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("play", "0010_alter_playsegment_active_seconds"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="playsession",
            index=models.Index(
                fields=["-last_seen_at"], name="play_playse_last_se_fa8495_idx"
            ),
        ),
    ]
