# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-04 17:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('creation_time', models.DateTimeField(verbose_name='Added at')),
                ('edit_time', models.DateTimeField(verbose_name='Last edit')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='Hidden')),
                ('is_readonly', models.BooleanField(default=False, verbose_name='Readonly')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Author')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Game')),
            ],
        ),
        migrations.CreateModel(
            name='GameAuthorRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbolic_id', models.SlugField()),
                ('title', models.CharField(max_length=255)),
                ('order', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GameTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbolic_id', models.SlugField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('show_in_search', models.BooleanField(default=False)),
                ('show_in_details', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameTagCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbolic_id', models.SlugField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('mutaly_exclusive', models.BooleanField(default=False)),
                ('allow_new_tags', models.BooleanField(default=False)),
                ('show_in_search', models.BooleanField(default=True)),
                ('show_in_details', models.BooleanField(default=True)),
                ('order', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GameURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(blank=True, null=True)),
                ('local_url', models.CharField(blank=True, max_length=255, null=True)),
                ('local_path', models.FilePathField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, max_length=255, null=True)),
                ('show_original', models.BooleanField(default=True)),
                ('show_local', models.BooleanField(default=True)),
                ('is_broken', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField()),
                ('use_count', models.IntegerField(default=0)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='URLCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbolic_id', models.SlugField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('allow_in_editor', models.BooleanField(default=True)),
                ('order', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='gameurl',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.URLCategory'),
        ),
        migrations.AddField(
            model_name='gameurl',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Game'),
        ),
        migrations.AddField(
            model_name='gameurl',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.URL'),
        ),
        migrations.AddField(
            model_name='gametag',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.GameTagCategory'),
        ),
        migrations.AddField(
            model_name='gameauthor',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.GameAuthorRole'),
        ),
    ]
