# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-03 19:47
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Title"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "release_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Release date"
                    ),
                ),
                (
                    "creation_time",
                    models.DateTimeField(
                        db_index=True, verbose_name="Added at"
                    ),
                ),
                (
                    "edit_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last edit"
                    ),
                ),
                (
                    "view_perm",
                    models.CharField(
                        default="@all",
                        max_length=255,
                        verbose_name="Game view permission",
                    ),
                ),
                (
                    "edit_perm",
                    models.CharField(
                        default="@auth",
                        max_length=255,
                        verbose_name="Edit permission",
                    ),
                ),
                (
                    "comment_perm",
                    models.CharField(
                        default="@auth",
                        max_length=255,
                        verbose_name="Comment permission",
                    ),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="GameAuthor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="games.Author",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="games.Game",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="GameAuthorRole",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "symbolic_id",
                    models.SlugField(
                        blank=True, max_length=32, null=True, unique=True
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=255)),
                ("order", models.SmallIntegerField(default=100)),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="GameComment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "foreign_username",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "foreign_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "foreign_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("creation_time", models.DateTimeField()),
                ("edit_time", models.DateTimeField(blank=True, null=True)),
                (
                    "subject",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("text", models.TextField()),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="games.Game",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="games.GameComment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="GameTag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "symbolic_id",
                    models.SlugField(
                        blank=True, max_length=32, null=True, unique=True
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="GameTagCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "symbolic_id",
                    models.SlugField(
                        blank=True, max_length=32, null=True, unique=True
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("allow_new_tags", models.BooleanField(default=True)),
                (
                    "show_in_edit_perm",
                    models.CharField(default="@all", max_length=255),
                ),
                (
                    "show_in_search_perm",
                    models.CharField(default="@all", max_length=255),
                ),
                (
                    "show_in_details_perm",
                    models.CharField(default="@all", max_length=255),
                ),
                ("order", models.SmallIntegerField(default=0)),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="GameURL",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="GameVote",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creation_time", models.DateTimeField()),
                ("edit_time", models.DateTimeField(blank=True, null=True)),
                ("game_finished", models.BooleanField()),
                ("play_time_mins", models.IntegerField()),
                ("star_rating", models.SmallIntegerField()),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="games.Game",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="URL",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "local_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "local_filename",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "original_url",
                    models.CharField(
                        blank=True, db_index=True, max_length=2048, null=True
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "content_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("ok_to_clone", models.BooleanField(default=True)),
                ("is_uploaded", models.BooleanField(default=False)),
                ("is_broken", models.BooleanField(default=False)),
                ("creation_date", models.DateTimeField()),
                ("use_count", models.IntegerField(default=0)),
                ("file_size", models.IntegerField(blank=True, null=True)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="URLCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "symbolic_id",
                    models.SlugField(
                        blank=True, max_length=32, null=True, unique=True
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=255)),
                ("allow_cloning", models.BooleanField(default=True)),
                ("order", models.SmallIntegerField(default=0)),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="InterpretedGameUrl",
            fields=[
                (
                    "original",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="games.GameURL",
                    ),
                ),
                (
                    "recoded_filename",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "recoded_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("recoding_date", models.DateTimeField()),
                ("is_playable", models.NullBooleanField()),
                (
                    "configuration_json",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.AddField(
            model_name="gameurl",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="games.URLCategory",
            ),
        ),
        migrations.AddField(
            model_name="gameurl",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="games.Game"
            ),
        ),
        migrations.AddField(
            model_name="gameurl",
            name="url",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="games.URL"
            ),
        ),
        migrations.AddField(
            model_name="gametag",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="games.GameTagCategory",
            ),
        ),
        migrations.AddField(
            model_name="gameauthor",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="games.GameAuthorRole",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="tags",
            field=models.ManyToManyField(blank=True, to="games.GameTag"),
        ),
        migrations.AlterUniqueTogether(
            name="gamevote",
            unique_together=set([("game", "user")]),
        ),
        migrations.AlterUniqueTogether(
            name="gametag",
            unique_together=set([("category", "name")]),
        ),
    ]
