# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-06 20:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Author",
            new_name="AuthorAlias",
        ),
    ]
