# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-07 07:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20171006_2019'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuthorAlias',
            new_name='PersonalityAlias',
        ),
    ]
