# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-07 08:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20171007_0723'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True, null=True)),
                ('view_perm', models.CharField(default='@all', max_length=255, verbose_name='Game view permission')),
                ('edit_perm', models.CharField(default='@auth', max_length=255, verbose_name='Edit permission')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='PersonalityUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='PersonalityURLCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbolic_id', models.SlugField(blank=True, max_length=32, null=True, unique=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('allow_cloning', models.BooleanField(default=False)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.RenameModel(
            old_name='URLCategory',
            new_name='GameURLCategory',
        ),
        migrations.AddField(
            model_name='personalityalias',
            name='hidden_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.PersonalityAlias'),
        ),
        migrations.AddField(
            model_name='personalityurl',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.PersonalityURLCategory'),
        ),
        migrations.AddField(
            model_name='personalityurl',
            name='personality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Personality'),
        ),
        migrations.AddField(
            model_name='personalityurl',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.URL'),
        ),
        migrations.AddField(
            model_name='personalityalias',
            name='personality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.Personality'),
        ),
    ]
