# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-11 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_personalityalias_is_blacklisted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalityalias',
            name='personality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.Personality'),
        ),
    ]
