# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-16 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_auto_20171111_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamecomment',
            name='foreign_id',
        ),
        migrations.RemoveField(
            model_name='gamecomment',
            name='foreign_url',
        ),
        migrations.RemoveField(
            model_name='gamecomment',
            name='foreign_username',
        ),
        migrations.AlterField(
            model_name='game',
            name='comment_perm',
            field=models.CharField(default='@all', max_length=255, verbose_name='Comment permission'),
        ),
    ]
