# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-23 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0007_auto_20171216_1909"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="release_date",
            field=models.DateField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="Release date",
            ),
        ),
    ]
