# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-26 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0009_auto_20171223_1638"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamecomment",
            name="username",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
