# Generated by Django 2.0.1 on 2018-01-13 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0014_remove_gamecomment_subject"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalityAliasRedirect",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "hidden_for",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="games.PersonalityAlias",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
    ]
