# Generated by Django 2.0.1 on 2018-01-13 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0015_personalityaliasredirect"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalityalias",
            name="keep_if_empty",
            field=models.BooleanField(default=False),
        ),
    ]
