# Generated by Django 2.0.1 on 2018-01-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0016_personalityalias_keep_if_empty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personalityaliasredirect",
            name="name",
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
