# Generated by Django 2.0.1 on 2018-02-16 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0018_auto_20180113_1613"),
    ]

    operations = [
        migrations.AlterField(
            model_name="url",
            name="ok_to_clone",
            field=models.BooleanField(default=False),
        ),
    ]
