# Generated by Django 2.0.1 on 2019-07-28 19:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("games", "0020_gamecommentvote"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="gamecommentvote",
            unique_together={("comment", "user")},
        ),
    ]
