# Generated by Django 6.0.1 on 2026-09-03 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def publish_existing_games(apps, schema_editor):
    Game = apps.get_model("games", "Game")
    Game.objects.all().update(state="PUBLISHED")


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0024_remove_interpreted_game_url"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="redirect_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="redirects",
                to="games.game",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="state",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PUBLISHED", "Published"),
                    ("REDIRECT", "Redirect"),
                ],
                db_index=True,
                default="DRAFT",
                max_length=16,
                verbose_name="Publication state",
            ),
        ),
        migrations.RunPython(
            publish_existing_games, migrations.RunPython.noop
        ),
        migrations.AddConstraint(
            model_name="game",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("redirect_to__isnull", False), ("state", "REDIRECT")
                    ),
                    models.Q(
                        ("redirect_to__isnull", True),
                        ("state__in", ["DRAFT", "PUBLISHED"]),
                    ),
                    _connector="OR",
                ),
                name="games_game_state_redirect_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="game",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("redirect_to__isnull", True),
                    models.Q(
                        ("pk", models.F("redirect_to_id")), _negated=True
                    ),
                    _connector="OR",
                ),
                name="games_game_redirect_not_self",
            ),
        ),
    ]
