# Generated by Django 6.0.1 on 2026-09-04 15:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0025_game_redirect_to_game_state_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="game",
            name="games_game_state_redirect_target",
        ),
        migrations.AlterField(
            model_name="game",
            name="state",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PUBLISHED", "Published"),
                    ("ABANDONED", "Abandoned"),
                    ("REDIRECT", "Redirect"),
                ],
                db_index=True,
                default="DRAFT",
                max_length=16,
                verbose_name="Publication state",
            ),
        ),
        migrations.AddConstraint(
            model_name="game",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("redirect_to__isnull", False), ("state", "REDIRECT")
                    ),
                    models.Q(
                        ("redirect_to__isnull", True),
                        ("state__in", ["DRAFT", "PUBLISHED", "ABANDONED"]),
                    ),
                    _connector="OR",
                ),
                name="games_game_state_redirect_target",
            ),
        ),
    ]
