# Generated by Django 6.0.1 on 2026-09-05 06:47

import django.db.models.deletion
from django.apps.registry import Apps
from django.conf import settings
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def move_gamerevision_to_games(
    apps: Apps, schema_editor: BaseDatabaseSchemaEditor
) -> None:
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        if connection.vendor == "postgresql":
            cursor.execute(
                "ALTER TABLE curation_gamerevision "
                "RENAME TO games_gamerevision;"
            )
            cursor.execute(
                "ALTER TABLE curation_gamerevision_used_sources "
                "RENAME TO games_gamerevision_used_sources;"
            )
            cursor.execute(
                "ALTER SEQUENCE IF EXISTS curation_gamerevision_id_seq "
                "RENAME TO games_gamerevision_id_seq;"
            )
            cursor.execute(
                "ALTER SEQUENCE IF EXISTS "
                "curation_gamerevision_used_sources_id_seq "
                "RENAME TO games_gamerevision_used_sources_id_seq;"
            )
            cursor.execute(
                "ALTER INDEX IF EXISTS curation_gamerevision_pkey "
                "RENAME TO games_gamerevision_pkey;"
            )
            cursor.execute(
                "ALTER INDEX IF EXISTS "
                "curation_gamerevision_used_sources_pkey "
                "RENAME TO games_gamerevision_used_sources_pkey;"
            )
            cursor.execute(
                "UPDATE games_gamerevision SET status = 'ACCEPTED' "
                "WHERE status = 'PUBLISHED';"
            )
        else:
            cursor.execute(
                "ALTER TABLE curation_gamerevision "
                "RENAME TO games_gamerevision;"
            )
            cursor.execute(
                "ALTER TABLE curation_gamerevision_used_sources "
                "RENAME TO games_gamerevision_used_sources;"
            )
            cursor.execute(
                "UPDATE games_gamerevision SET status = 'ACCEPTED' "
                "WHERE status = 'PUBLISHED';"
            )


def reverse_move_gamerevision(
    apps: Apps, schema_editor: BaseDatabaseSchemaEditor
) -> None:
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        if connection.vendor == "postgresql":
            cursor.execute(
                "UPDATE games_gamerevision SET status = 'PUBLISHED' "
                "WHERE status = 'ACCEPTED';"
            )
            cursor.execute(
                "ALTER INDEX IF EXISTS "
                "games_gamerevision_used_sources_pkey "
                "RENAME TO curation_gamerevision_used_sources_pkey;"
            )
            cursor.execute(
                "ALTER INDEX IF EXISTS games_gamerevision_pkey "
                "RENAME TO curation_gamerevision_pkey;"
            )
            cursor.execute(
                "ALTER SEQUENCE IF EXISTS "
                "games_gamerevision_used_sources_id_seq "
                "RENAME TO curation_gamerevision_used_sources_id_seq;"
            )
            cursor.execute(
                "ALTER SEQUENCE IF EXISTS games_gamerevision_id_seq "
                "RENAME TO curation_gamerevision_id_seq;"
            )
            cursor.execute(
                "ALTER TABLE games_gamerevision_used_sources "
                "RENAME TO curation_gamerevision_used_sources;"
            )
            cursor.execute(
                "ALTER TABLE games_gamerevision "
                "RENAME TO curation_gamerevision;"
            )
        else:
            cursor.execute(
                "UPDATE games_gamerevision SET status = 'PUBLISHED' "
                "WHERE status = 'ACCEPTED';"
            )
            cursor.execute(
                "ALTER TABLE games_gamerevision_used_sources "
                "RENAME TO curation_gamerevision_used_sources;"
            )
            cursor.execute(
                "ALTER TABLE games_gamerevision "
                "RENAME TO curation_gamerevision;"
            )


class Migration(migrations.Migration):
    dependencies = [
        (
            "curation",
            "0037_remove_gamerevision_curation_gamerevision_one_proposed_per_game",
        ),
        (
            "games",
            "0026_remove_game_games_game_state_redirect_target_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="GameRevision",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "created_at",
                            models.DateTimeField(verbose_name="Created at"),
                        ),
                        (
                            "published_at",
                            models.DateTimeField(
                                blank=True,
                                null=True,
                                verbose_name="Published at",
                            ),
                        ),
                        (
                            "status",
                            models.CharField(
                                choices=[
                                    ("PROPOSED", "Proposed"),
                                    ("ACCEPTED", "Accepted"),
                                    ("REJECTED", "Rejected"),
                                ],
                                max_length=16,
                                verbose_name="Status",
                            ),
                        ),
                        (
                            "origin",
                            models.CharField(
                                choices=[
                                    ("AUTO_IMPORT", "Automatic import"),
                                    ("MANUAL_EDIT", "Manual edit"),
                                    ("USER_SUGGESTION", "User suggestion"),
                                    ("BACKFILL", "Backfill"),
                                    ("ROLLBACK", "Rollback"),
                                    ("PARTIAL_ROLLBACK", "Partial rollback"),
                                    ("REAPPLICATION", "Reapplication"),
                                    (
                                        "PARTIAL_REAPPLY",
                                        "Partial reapplication",
                                    ),
                                ],
                                max_length=16,
                                verbose_name="Origin",
                            ),
                        ),
                        (
                            "passes",
                            models.JSONField(
                                default=list, verbose_name="Passes"
                            ),
                        ),
                        (
                            "previous_canonical_text",
                            models.TextField(
                                blank=True,
                                null=True,
                                verbose_name="Previous canonical text",
                            ),
                        ),
                        (
                            "canonical_text",
                            models.TextField(verbose_name="Canonical text"),
                        ),
                        (
                            "created_by",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="created_game_revisions",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            "game",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="games.game",
                            ),
                        ),
                        (
                            "published_by",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            "used_sources",
                            models.ManyToManyField(
                                blank=True, to="curation.gamesourcefetch"
                            ),
                        ),
                    ],
                    options={
                        "default_permissions": (),
                    },
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    move_gamerevision_to_games, reverse_move_gamerevision
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="gamerevision",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "PROPOSED")),
                fields=("game",),
                name="games_gamerevision_one_proposed_per_game",
            ),
        ),
    ]
