# Generated by Django 6.0.1 on 2026-09-05 07:17

import django.db.models.deletion
from django.apps.registry import Apps
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def initialize_published_revision(
    apps: Apps, schema_editor: BaseDatabaseSchemaEditor
) -> None:
    Game = apps.get_model("games", "Game")
    GameRevision = apps.get_model("games", "GameRevision")
    db_alias = schema_editor.connection.alias

    latest_by_game: dict[int, int] = {}
    for rev_id, game_id in (
        GameRevision.objects
        .using(db_alias)
        .filter(status="ACCEPTED")
        .order_by("game_id", "-published_at", "-created_at", "-id")
        .values_list("id", "game_id")
    ):
        latest_by_game.setdefault(game_id, rev_id)

    for game_id, rev_id in latest_by_game.items():
        Game.objects.using(db_alias).filter(id=game_id).update(
            published_revision_id=rev_id
        )


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0027_gamerevision"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="published_revision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="games.gamerevision",
                verbose_name="Published revision",
            ),
        ),
        migrations.RunPython(
            initialize_published_revision,
            migrations.RunPython.noop,
        ),
    ]
