# Generated by Django 6.0.1 on 2026-09-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0028_game_published_revision"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamerevision",
            name="origin",
            field=models.CharField(
                choices=[
                    ("AUTO_IMPORT", "Automatic import"),
                    ("MANUAL_EDIT", "Manual edit"),
                    ("USER_SUGGESTION", "User suggestion"),
                    ("BACKFILL", "Backfill"),
                    ("ROLLBACK", "Rollback"),
                    ("PARTIAL_ROLLBACK", "Partial rollback"),
                    ("REAPPLICATION", "Reapplication"),
                    ("PARTIAL_REAPPLY", "Partial reapplication"),
                    ("CLONE", "Clone"),
                    ("MERGE", "Merge"),
                ],
                max_length=16,
                verbose_name="Origin",
            ),
        ),
    ]
