# Generated by Django 6.0.1 on 2026-09-05 17:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0030_alter_gamerevision_origin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="comment_perm",
        ),
        migrations.RemoveField(
            model_name="game",
            name="delete_perm",
        ),
        migrations.RemoveField(
            model_name="game",
            name="edit_perm",
        ),
        migrations.RemoveField(
            model_name="game",
            name="view_perm",
        ),
        migrations.RemoveField(
            model_name="game",
            name="vote_perm",
        ),
        migrations.RemoveField(
            model_name="gametagcategory",
            name="show_in_details_perm",
        ),
        migrations.RemoveField(
            model_name="gametagcategory",
            name="show_in_edit_perm",
        ),
        migrations.RemoveField(
            model_name="gametagcategory",
            name="show_in_search_perm",
        ),
        migrations.RemoveField(
            model_name="personality",
            name="edit_perm",
        ),
        migrations.RemoveField(
            model_name="personality",
            name="view_perm",
        ),
    ]
