# Generated by Django 6.0.1 on 2026-09-05 17:26

from django.db import migrations


def delete_admin_tag_category(apps, schema_editor):
    GameTagCategory = apps.get_model("games", "GameTagCategory")
    GameTagCategory.objects.filter(symbolic_id="admin").delete()


class Migration(migrations.Migration):
    dependencies = [
        (
            "games",
            "0031_remove_game_comment_perm_remove_game_delete_perm_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(
            delete_admin_tag_category, migrations.RunPython.noop
        ),
    ]
