# Generated by Django 6.0.1 on 2026-09-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0034_alter_gamerevision_origin"),
    ]

    operations = [
        migrations.AddField(
            model_name="gametagcategory",
            name="is_internal",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
