# Generated by Django 6.0.1 on 2026-09-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0036_create_service_tag_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamerevision",
            name="source_snapshots",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
