# Generated by Django 6.0.1 on 2026-09-27 15:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0037_gamerevision_source_snapshots"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoredFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_hash",
                    models.CharField(
                        db_index=True, max_length=64, unique=True
                    ),
                ),
                (
                    "storage_path",
                    models.CharField(max_length=512, unique=True),
                ),
                ("file_size", models.PositiveBigIntegerField()),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.AddField(
            model_name="url",
            name="failing_since",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="url",
            name="last_attempt",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="url",
            name="last_error",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="URLFetch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "content_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "first_fetch",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "last_fetch",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "stored_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fetches",
                        to="games.storedfile",
                    ),
                ),
                (
                    "url",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fetches",
                        to="games.url",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
                "indexes": [
                    models.Index(
                        fields=["url", "-last_fetch"],
                        name="games_urlfe_url_id_3ba097_idx",
                    )
                ],
            },
        ),
    ]
