# Generated by Django 6.0.1 on 2026-09-27 20:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0039_fetch_urls_periodic_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="url",
            name="local_url",
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
