# Generated by Django 6.0.1 on 2026-09-30 20:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0040_alter_url_local_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="url",
            name="ok_to_clone",
        ),
    ]
