# Generated by Django 6.0.1 on 2026-09-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0040_alter_url_local_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="urlfetch",
            name="bad_fetch",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="urlfetch",
            index=models.Index(
                fields=["url", "bad_fetch", "-last_fetch"],
                name="games_urlfe_url_id_9ef6b5_idx",
            ),
        ),
    ]
