# Generated by Django 6.0.1 on 2026-10-01 17:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0041_remove_url_ok_to_clone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="url",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="url",
            name="file_size",
        ),
        migrations.RemoveField(
            model_name="url",
            name="is_broken",
        ),
        migrations.RemoveField(
            model_name="url",
            name="local_filename",
        ),
        migrations.RemoveField(
            model_name="url",
            name="local_url",
        ),
        migrations.RemoveField(
            model_name="url",
            name="original_filename",
        ),
    ]
